MODULE Directives
  IMPLICIT NONE
  INTEGER, PARAMETER :: IA = ICHAR('a')
  INTEGER, PARAMETER :: IAA = ICHAR('A')
  INTEGER, PARAMETER :: IZZ = ICHAR('Z')  
  INTEGER, PARAMETER :: LINE_WIDTH = 128
  CHARACTER, PARAMETER :: COMMENT_SYMBOL = '#'
  CHARACTER, PARAMETER :: ASSIGN_SYMBOL = ':'
  CHARACTER(LEN=*), PARAMETER :: DIR_TIMESTEPS = 'timesteps'
  CHARACTER(LEN=*), PARAMETER :: DIR_DELTA_TIMESTEPS = 'delta timestep'
  CHARACTER(LEN=*), PARAMETER :: DIR_SIM_SIZE = 'simulation size'
  CHARACTER(LEN=*), PARAMETER :: DIR_POSSION_RATE = 'poisson waiting rate'
  CHARACTER(LEN=*), PARAMETER :: DIR_POSSION_LBOUND = 'poisson waiting lower bound'
  CHARACTER(LEN=*), PARAMETER :: DIR_NUM_ATOMS = 'number of atoms'
  CHARACTER(LEN=*), PARAMETER :: DIR_GENERATE_POS = 'generating position'
  CHARACTER(LEN=*), PARAMETER :: DIR_GENERATE_CUT = 'generating distance cut'
  
  CHARACTER(LEN=*), PARAMETER :: DIR_FIXED_POTENTIAL = 'fixed potential'
  CHARACTER(LEN=*), PARAMETER :: POTENTIAL_GAUSSIAN = 'gaussian'
  CHARACTER(LEN=*), PARAMETER :: POTENTIAL_BIAS_VOLTAGE = 'bias_voltage'
  
  CHARACTER(LEN=*), PARAMETER :: DIR_CURRENT_PROBE_POS = 'current probe position'
  CHARACTER(LEN=*), PARAMETER :: DIR_VISCOSITY = 'viscosity'  

  CHARACTER(LEN=*), PARAMETER :: DIR_GNUPLOT = 'gnuplot'
  CHARACTER(LEN=*), PARAMETER :: GP_BOUNDINGS = 'boundings'
END MODULE Directives
